# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049fafb5838e6dff7e0413ccce076b2f53e0bd00ddc223f8298b7bff1ee81707fabf868d8c0f155a05c02fdb1f8a374050c1a764120b75893cce13fc8bd362d7

test:
  secret_key_base: fe977ab10f6d75097c0adc7313b838c3c8af7b4e512e0b79f042643c39aa0a7d59b9bbefe8cea0426d6fd5429351d7947a7e85611ad78c6b7ffe1f0c5aeb0085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
